--- #YAML:1.0
name:               RTF-HTML-Converter-API
version:            0.1
abstract:           OO API to Philippe Verdret's RTF::HTML::Convertor
author:
    - Lee Goddard <lgoddard@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    RTF::HTML::Converter:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
